### ISSUE TITLE
Which model are we using when we choose "GPT-4"?

### ISSUE THREAD

**Issue by singularitti** [JuniperPhoton/Photon-AI-Translator-Support#3]
OpenAI recently published the `GPT-4-1106-preview` model, which is much cheaper than the previous GPT-4 models. When we choose it, are we using the latest model or the old model?

<img width="382" alt="image" src="https://github.com/JuniperPhoton/Photon-AI-Translator-Support/assets/25192197/5ba89c23-8308-402f-b5be-3c3ac9836dd7">

**Comment by JuniperPhoton** [comment]
It's the first GPT-4 release. I haven't updated this app to support the recently updated models. 

Thanks for you notice and I will work on that :)

**Comment by singularitti** [comment]
Cool! Thanks for the information and I hope it can be updated soon.

**Comment by JuniperPhoton** [comment]
Hi again. I checkout the [doc](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) of the new GPT-4, did you refer to this `gpt-4-1106-preview`? 

It seems like it's on preview, and this app uses my [PhotonOpenAIKit](https://github.com/JuniperPhoton/PhotonOpenAIKit) to communicate with OpenAPI. Since the model is not eligible for production currently, I won't add this to the enum defined in the production-ready library. Instead, I may add an option to let users input the model by themselves.

<img width="845" alt="image" src="https://github.com/JuniperPhoton/Photon-AI-Translator-Support/assets/7578386/83051fff-ad09-4bd9-9dc3-357d96e4afbe">

**Comment by singularitti** [comment]
> did you refer to this gpt-4-1106-preview?

Yes, this model is much cheaper.

> Since the model is not eligible for production currently, I won't add this to the enum defined in the production-ready library. 

No problem!

> Instead, I may add an option to let users input the model by themselves.

Sounds fantastic!

**Comment by JuniperPhoton** [comment]
This new v2.5.5 is released for all platforms.

**Comment by singularitti** [comment]
Thank you!
